openapi: 3.0.4
info:
  title: Did You Mean
  description: Did You Mean is a simple tool for correcting spelling mistakes. It returns the corrected text.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/didyoumean:
    get:
      summary: Suggest Did You Mean
      description: Did You Mean is a simple tool for correcting spelling mistakes. It returns the corrected text.
      operationId: didyoumean
      parameters:
      - name: query
        in: query
        schema:
          type: string
        required: true
        description: The text you want to check for spelling mistakes
        example: what weather today is
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  query: what weather today is
                  didYouMean:
                  - what is the weather today
                  - what's the weather today
                  - what will the weather be today
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
